// <auto-generated />
namespace TB.Kutuphane.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createDatabae : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createDatabae));
        
        string IMigrationMetadata.Id
        {
            get { return "202103221919455_createDatabae"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
